name:                hideout-backend
version:             0.1.0.0
github:              "githubuser/hideout-backend"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hideout-backend#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- cryptonite
- containers
- generic-lens
- lens
- mtl
- servant
- servant-server
- stm
- wai
- warp
- wai-cors

library:
  source-dirs: src

executables:
  hideout-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hideout-backend

tests:
  hideout-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hideout-backend
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
